# -*- coding: utf-8 -*-
"""FormulaIT_Task11_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaBSGOE2PT80_JuZPevphSSnz_J6Nbv_
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import root_mean_squared_error
import pandas as pd
import numpy as np

def r2_rmse_mean(file_name):
  df = pd.read_csv(file_name)
  df = df.fillna(df.mean(numeric_only=True))
  x = df[['Year', 'Engine HP', 'Engine Cylinders', 'highway MPG', 'city mpg', 'Popularity']]
  y = df['MSRP']
  x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=42)
  model = LinearRegression()
  model.fit(x_train,y_train)
  y_pred = model.predict(x_test)
  r2 = r2_score(y_test,y_pred)
  rmse = root_mean_squared_error(y_test,y_pred)
  y_train_mean = y_train.mean()
  y_mean = [y_train_mean]*len(y_test)
  r2_mean = r2_score(y_test, y_mean)
  rmse_mean = root_mean_squared_error(y_test, y_mean)
  return [r2,rmse,r2_mean,rmse_mean]


r2, rmse, r2_mean, rmse_mean = r2_rmse_mean('data.csv')

print(f'R2 model = {r2}')
print(f'RMSE model = {rmse}')
print(f'R2 mean model = {r2_mean}')
print(f'rmse mean model = {rmse_mean}\n')
print(f'Difference between RMSE_LinearRegression and StupidModel = {rmse - rmse_mean}')

# Линейная регрессия предсказывает лучше, чем глупая модель

